// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: book.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBook = `-- name: DeleteBook :execrows
DELETE FROM books
Where id = $1
`

func (q *Queries) DeleteBook(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBook, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const fullUpdateBook = `-- name: FullUpdateBook :execrows
UPDATE books
SET title = $2, author = $3, num_pages = $4, rating = $5
WHERE id = $1
`

type FullUpdateBookParams struct {
	ID       int64
	Title    pgtype.Text
	Author   pgtype.Text
	NumPages pgtype.Int4
	Rating   pgtype.Float8
}

func (q *Queries) FullUpdateBook(ctx context.Context, arg FullUpdateBookParams) (int64, error) {
	result, err := q.db.Exec(ctx, fullUpdateBook,
		arg.ID,
		arg.Title,
		arg.Author,
		arg.NumPages,
		arg.Rating,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBookByID = `-- name: GetBookByID :one
SELECT id, title, author, num_pages, rating from books
WHERE id = $1
`

func (q *Queries) GetBookByID(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRow(ctx, getBookByID, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.NumPages,
		&i.Rating,
	)
	return i, err
}

const insertBook = `-- name: InsertBook :one
INSERT INTO books(title, author, num_pages, rating)
VALUES($1,$2,$3,$4)
RETURNING id, title, author, num_pages, rating
`

type InsertBookParams struct {
	Title    pgtype.Text
	Author   pgtype.Text
	NumPages pgtype.Int4
	Rating   pgtype.Float8
}

func (q *Queries) InsertBook(ctx context.Context, arg InsertBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, insertBook,
		arg.Title,
		arg.Author,
		arg.NumPages,
		arg.Rating,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.NumPages,
		&i.Rating,
	)
	return i, err
}

const listAllBooks = `-- name: ListAllBooks :many
SELECT id, title, author, num_pages, rating from books
ORDER BY id
`

func (q *Queries) ListAllBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.Query(ctx, listAllBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.NumPages,
			&i.Rating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooks = `-- name: ListBooks :many
SELECT id, title, author, num_pages, rating from books
WHERE id>= $1 AND id<=$2
ORDER BY id
`

type ListBooksParams struct {
	ID   int64
	ID_2 int64
}

func (q *Queries) ListBooks(ctx context.Context, arg ListBooksParams) ([]Book, error) {
	rows, err := q.db.Query(ctx, listBooks, arg.ID, arg.ID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.NumPages,
			&i.Rating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
