// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID       int64
	Title    pgtype.Text
	Author   pgtype.Text
	NumPages pgtype.Int4
	Rating   pgtype.Float8
}
