// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	DeleteBook(ctx context.Context, id int64) (int64, error)
	FullUpdateBook(ctx context.Context, arg FullUpdateBookParams) (int64, error)
	GetBookByID(ctx context.Context, id int64) (Book, error)
	InsertBook(ctx context.Context, arg InsertBookParams) (Book, error)
	ListAllBooks(ctx context.Context) ([]Book, error)
	ListBooks(ctx context.Context, arg ListBooksParams) ([]Book, error)
}

var _ Querier = (*Queries)(nil)
